env:
  node: true
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
ignorePatterns:
  - 'auto-api'
  - 'es'
  - 'lib'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 10
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
rules:
  'import/no-named-as-default': off
  'import/order':
    - error
    - alphabetize:
        order: 'ignore'
      groups:
        - - builtin
          - external
        - internal
        - parent
        - sibling
        - index
        - object
      'newlines-between': always-and-inside-groups
  'sort-imports':
    - error
    - allowSeparatedGroups: true
      ignoreCase: true
      ignoreDeclarationSort: true
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-non-null-assertion': off
settings:
  'import/resolver':
    alias:
      map:
        - - '@'
          - './src'
        - - 'tests'
          - './tests'
      extensions:
        - '.ts'
        - '.js'
